---
  language: go
  sudo: false
  notifications:
    email: false
  go:
    - 1.5
    - 1.6
    - 1.7
    - 1.8
    - tip
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  install:
    - go get github.com/golang/lint/golint
  script:
    - go build -v
    - go vet $(go list ./...)
    - test -z "$(golint ./... | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | tee /dev/stderr)"
    - go test $(go list ./...)
